In [3]:
import pandas as pd
df=pd.read_csv("telecom_churn.csv")
df.head(5)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
1,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
2,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
3,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
4,AL,118,510,Yes,No,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False

In [7]:
df.describe(include="all")
df.shape

(3332, 20)

In [8]:
column_name=df.columns
for i in column_name:
    print(i)
len(column_name)

State
Account length
Area code
International plan
Voice mail plan
Number vmail messages
Total day minutes
Total day calls
Total day charge
Total eve minutes
Total eve calls
Total eve charge
Total night minutes
Total night calls
Total night charge
Total intl minutes
Total intl calls
Total intl charge
Customer service calls
Churn

20

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3332 entries, 0 to 3331
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State                   3332 non-null   object
 1   Account length          3332 non-null   int64
 2   Area code               3332 non-null   int64
 3   International plan      3332 non-null   object
 4   Voice mail plan         3332 non-null   object
 5   Number vmail messages   3332 non-null   int64
 6   Total day minutes       3332 non-null   float64
 7   Total day calls         3332 non-null   int64
 8   Total day charge        3332 non-null   float64
 9   Total eve minutes       3332 non-null   float64
 10  Total eve calls         3332 non-null   int64
 11  Total eve charge        3332 non-null   float64
 12  Total night minutes     3332 non-null   float64
 13  Total night calls       3332 non-null   int64
 14  Total night charge      3332 non-null   float64
 15  Total intl minutes      3332 non-null   float64
 16  Total intl calls        3332 non-null   int64
 17  Total intl charge       3332 non-null   float64
 18  Customer service calls  3332 non-null   int64
 19  Churn                   3332 non-null   bool
dtypes: bool(1), float64(8), int64(8), object(3)
memory usage: 498.0+ KB

In [10]:
df["Churn"]=df["Churn"].astype("int64")

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3332 entries, 0 to 3331
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State                   3332 non-null   object
 1   Account length          3332 non-null   int64
 2   Area code               3332 non-null   int64
 3   International plan      3332 non-null   object
 4   Voice mail plan         3332 non-null   object
 5   Number vmail messages   3332 non-null   int64
 6   Total day minutes       3332 non-null   float64
 7   Total day calls         3332 non-null   int64
 8   Total day charge        3332 non-null   float64
 9   Total eve minutes       3332 non-null   float64
 10  Total eve calls         3332 non-null   int64
 11  Total eve charge        3332 non-null   float64
 12  Total night minutes     3332 non-null   float64
 13  Total night calls       3332 non-null   int64
 14  Total night charge      3332 non-null   float64
 15  Total intl minutes      3332 non-null   float64
 16  Total intl calls        3332 non-null   int64
 17  Total intl charge       3332 non-null   float64
 18  Customer service calls  3332 non-null   int64
 19  Churn                   3332 non-null   int64
dtypes: float64(8), int64(9), object(3)
memory usage: 520.8+ KB

In [12]:
df["Churn"].value_counts()

Churn
0    2849
1     483
Name: count, dtype: int64

In [13]:
df["Churn"].value_counts(normalize=True)

Churn
0    0.855042
1    0.144958
Name: proportion, dtype: float64

In [14]:
df.sort_values(by=["Churn","Total day charge"], ascending=[True,False])

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
687,MN,13,510,No,Yes,21,315.6,105,53.65,208.9,71,17.76,260.1,123,11.70,12.1,3,3.27,3,0
2258,NC,210,415,No,Yes,31,313.8,87,53.35,147.7,103,12.55,192.7,97,8.67,10.1,7,2.73,3,0
533,LA,67,510,No,No,0,310.4,97,52.77,66.5,123,5.65,246.5,99,11.09,9.2,10,2.48,4,0
574,SD,114,415,No,Yes,36,309.9,90,52.68,200.3,89,17.03,183.5,105,8.26,14.2,2,3.83,1,0
2857,AL,141,510,No,Yes,28,308.0,123,52.36,247.8,128,21.06,152.9,103,6.88,7.4,3,2.00,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1836,NH,117,510,Yes,No,0,54.2,100,9.21,303.2,84,25.77,171.8,84,7.73,8.6,2,2.32,1,1
2172,KS,47,510,Yes,No,0,47.8,120,8.13,178.9,123,15.21,152.6,96,6.87,13.3,7,3.59,0,1
2157,FL,166,510,Yes,No,0,47.7,89,8.11,264.4,95,22.47,235.2,97,10.58,13.2,3,3.56,0,1
1530,DE,138,510,Yes,No,0,46.5,104,7.91,186.0,114,15.81,167.5,95,7.54,9.6,4,2.59,4,1
1344,SD,98,415,No,No,0,0.0,0,0.00,159.6,130,13.57,167.1,88,7.52,6.8,1,1.84,4,1

In [18]:
churned_users=df[df["Churn"]==1]
numerica_features=churned_users.select_dtypes("number")
avg_val=numerica_features.mean()
avg_val

Account length            102.664596
Area code                 437.817805
Number vmail messages       5.115942
Total day minutes         206.914079
Total day calls           101.335404
Total day charge           35.175921
Total eve minutes         212.410145
Total eve calls           100.561077
Total eve charge           18.054969
Total night minutes       205.231677
Total night calls         100.399586
Total night charge          9.235528
Total intl minutes         10.700000
Total intl calls            4.163561
Total intl charge           2.889545
Customer service calls      2.229814
Churn                       1.000000
dtype: float64

In [22]:
churned_users=df[df["Churn"]==1]
avg_spend=churned_users["Total day minutes"].mean()
print(avg_spend)

206.91407867494823

In [23]:
data=df[(df["Churn"]==0) & (df["International plan"]=="No")]
max_len=data["Total intl calls"].max()
print(max_len)

19

In [25]:
df.head(1)
df.tail(1)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3331,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,82,22.6,241.4,77,10.86,13.7,4,3.7,0,0

In [29]:
df["total_calls"]=df[["Total day calls","Total eve calls","Total night calls","Total intl calls"]].sum(axis=1)
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,total_calls
0,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,...,16.62,254.4,103,11.45,13.7,3,3.70,1,0,332
1,NJ,137,415,No,No,0,243.4,114,41.38,121.2,...,10.30,162.6,104,7.32,12.2,5,3.29,0,0,333
2,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,...,5.26,196.9,89,8.86,6.6,7,1.78,2,0,255
3,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,...,12.61,186.9,121,8.41,10.1,3,2.73,3,0,359
4,AL,118,510,Yes,No,0,223.4,98,37.98,220.6,...,18.75,203.9,118,9.18,6.3,6,1.70,0,0,323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,AZ,192,415,No,Yes,36,156.2,77,26.55,215.5,...,18.32,279.1,83,12.56,9.9,6,2.67,2,0,292
3328,WV,68,415,No,No,0,231.1,57,39.29,153.4,...,13.04,191.3,123,8.61,9.6,4,2.59,3,0,239
3329,RI,28,510,No,No,0,180.8,109,30.74,288.8,...,24.55,191.9,91,8.64,14.1,6,3.81,2,0,264
3330,CT,184,510,Yes,No,0,213.8,105,36.35,159.6,...,13.57,139.2,137,6.26,5.0,10,1.35,2,0,336
3331,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,...,22.60,241.4,77,10.86,13.7,4,3.70,0,0,276

In [30]:
new=df.groupby("Area code")["Total day minutes"].mean()
new

Area code
408    177.175418
415    181.542140
510    178.787619
Name: Total day minutes, dtype: float64

In [32]:
filtered_data=df[df['Customer service calls']<3]
median_data=filtered_data["Total night minutes"].median()
print(median_data)

201.4

In [34]:
filtered_data=df[df['Voice mail plan']=="No"]
per_total=filtered_data['Total day calls'].quantile(0.75)
print(per_total)

114.0

In [37]:
df["Area code"].nunique()
df["Area code"].value_counts()

Area code
415    1654
510     840
408     838
Name: count, dtype: int64

In [39]:
data=df[df["Number vmail messages"]>10].groupby("State").size().div(df.groupby("State").size())*100
data

State
AK    30.769231
AL    26.250000
AR    25.454545
AZ    29.687500
CA    32.352941
CO    28.787879
CT    28.378378
DC    33.333333
DE    22.950820
FL    31.746032
GA    35.185185
HI    28.301887
IA    27.272727
ID    36.986301
IL    25.862069
IN    25.352113
KS    26.086957
KY    23.728814
LA    25.490196
MA    29.230769
MD    24.285714
ME    27.419355
MI    28.767123
MN    28.571429
MO    26.984127
MS    32.307692
MT    35.294118
NC    29.411765
ND    33.870968
NE    27.868852
NH    28.571429
NJ    29.411765
NM    22.580645
NV    21.212121
NY    21.686747
OH    33.333333
OK    27.868852
OR    21.794872
PA    26.666667
RI    27.692308
SC    28.333333
SD    35.000000
TN    26.415094
TX    22.222222
UT    27.777778
VA    23.376623
VT    21.917808
WA    15.151515
WI    29.487179
WV    27.358491
WY    22.077922
dtype: float64

In [44]:
data=df.groupby("State")["Total intl charge"].max()
data

print(data.idxmax(), data.max())

ME 5.4